spring.application.name=12_Using_data_sources_Spring

// Example of using MySql instead of H2db
spring.datasource.url=jdbc:mysql://localhost:3306/your_database_name
spring.datasource.username=your_username
spring.datasource.password=your_password
spring.sql.init.mode=always

# Custom DataSource Configuration (for ProjectConfig class)
# custom.datasource.url=jdbc:mysql://localhost:3306/your_database_name
# custom.datasource.username=your_username
# custom.datasource.password=your_password